name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy over SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_HOST_PORT }}
        script: |
          set -e
          cd /home/debian/src/shounentimejs || git clone git@github.com:michaeldchin/shounentimejs.git /home/debian/src/shounentimejs
          cd /home/debian/src/shounentimejs
          git pull origin master
          npm ci --production
          sudo systemctl restart shounentime
